### ISSUE TITLE
rs_create_table throwing an error $ Code     : chr "AccessDenied"

### ISSUE THREAD

**Issue by rmodepalli** [sicarul/redshiftTools#13]
Hi I am trying write R dataframe to Redshift table by using below function from EC2 instance.

rs_create_table(seg_mem_model, dbcon=conn, table_name='segmenattion_model', bucket=s3_bucket, 
                   region = s3_region, iam_role_arn = aws_iam_role, split_files=4)

I got below error.

[1] "The provided data.frame has 1805422 rows"
List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "A096AC9FC2F163A7"
 $ HostId   : chr "CkxoZsK8sE2wW/jMb5vXSOp2Cb1SLvzVZ2xlaiA+h9dfliJBSkoW+lsmot/TWbYXcTaqM2mAhDA="
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "A096AC9FC2F163A7"
  ..$ x-amz-id-2       : chr "CkxoZsK8sE2wW/jMb5vXSOp2Cb1SLvzVZ2xlaiA+h9dfliJBSkoW+lsmot/TWbYXcTaqM2mAhDA="
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Mon, 22 Jan 2018 22:09:52 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).

Please find below the sessionInfo() output.

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] redshiftTools_0.3.900 RPostgreSQL_0.6-2     DBI_0.7-13            RPostgres_1.0-4       aws.s3_0.3.3         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15        digest_0.6.14       aws.signature_0.3.5 R6_2.2.2            pillar_1.1.0        httr_1.3.1          rlang_0.1.6         curl_3.1           
 [9] blob_1.1.0          xml2_1.1.1          tools_3.4.3         bit64_0.9-7         bit_1.1-12          hms_0.4.0           compiler_3.4.3      pkgconfig_2.0.1    
[17] base64enc_0.1-3     tibble_1.4.1

**Comment by sicarul** [comment]
Hey @rmodepalli make sure the access keys you are using can access the S3 bucket you are using, most probably it doesn't have access to read and write to it, that error appears when the AWS keys used do not have access

https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html

**Comment by rmodepalli** [comment]
Sicarul, 

We have to use IAM Role instead of access key and secret key. My EC2 instance is assigned with IAM Role and I am able to copy the files using aws CLI. I am getting the error when I use below R function
rs_create_table(seg_mem_model, dbcon=conn, table_name='segmenattion_model', bucket=s3_bucket,
 region = s3_region, iam_role_arn = aws_iam_role, split_files=4)

**Comment by sicarul** [comment]
Hmm i think it's because the iam role isn't used when copying the files, i'll have to review by April, if you can fix it i can review your PR before.

**Comment by rkbarney** [comment]
I think this may have soimething to do with this known aws.s3 bug: https://github.com/cloudyr/aws.s3/issues/122

Have we tried  `get_object(wanted_file, wanted_bucket, check_region = F)`?

https://gist.github.com/gm3dmo/418320c79f48005c740e7ae148a3883c

**Comment by sicarul** [comment]
@rmodepalli if you can please check if this issue exists in the latest version

**Comment by sicarul** [comment]
I'll assume this is fixed since we are using it at Auth0 in production, let me know otherwise

**Comment by vikramgk9** [comment]
Hello,

I would like to know if this issue was fixed. I am getting this error: Error in parse_aws_s3_response(r, Sig, verbose = verbose) : Forbidden (HTTP 403).
The access keys I am using is able to access the S3 Bucket and has read and write access into it. When i search for this error, there was a mention of setting check_region = FALSE in `get_object()` or `s3readRDS()`, but `rs_create_table` does not recognize it as a valid parameter to pass into the function. But the function is obviously writing temporarily into the S3 bucket and then copying into Redshift? How do we get around this issue?

**Comment by sicarul** [comment]
Can you try updating aws.s3 to the latest version and try again?

**Comment by vikramgk9** [comment]
By latest version do you mean aws.s3_0.3.12? I am already running on that version and but still have the problem.

**Comment by vikramgk9** [comment]
Please let me know if there is any update on this issue

**Comment by sicarul** [comment]
@vikramgk9 have you tried uploading to the same bucket with the same S3 credentials using aws.s3 as you are giving to the copy statement? I'm asking since the check_region issue did exist but has been solved in the latest versions of aws.s3.

**Comment by lsabreu96** [comment]
hi, @sicarul ,

I'm facing the same issue. Yesterday as I had not updated packages, I was able to write database to Redshift, now as I've updated the packages this error is also popping up to me.
